### ISSUE TITLE
Эпик "Корзина"

### ISSUE THREAD

**Issue by MarinaKolbina** [miamib34ch/YP-CP-FakeNFT#2]
- [ ] [Добавление новой страницы + изменение иконки в таббар](https://github.com/users/miamib34ch/projects/1/views/1?pane=issue&itemId=34395659) 1 час
- [ ] [Верстка корзины (полной и пустой) ](https://github.com/users/miamib34ch/projects/1/views/1?pane=issue&itemId=34396294) 3 часа

**Comment by miamib34ch** [comment]
Ожидаемое время 22 часа 50 минут
